#!/bin/bash

OPTIONS=$*
REP_SCR=$(dirname $0)
FILE_SCR=$(basename $0)


echo "tache cron du depot"

echo "GITHUB pull"
cd $REP_SCR
git pull

echo "execution du script : linux-postinstall"
$REP_SCR/linux-postinstall/main.sh

